#!/usr/bin/env bash
# day_trader_pro/menu_registry.sh — GENERATED DRAFT, review before use
# Generated by tools/menu_extract.py from devtools.sh.
#
# THERE ARE NO NUMBERS IN THIS FILE. devtools.sh assigns them at
# render time from list position, so reordering this list, inserting
# a section, or deleting an item cannot desynchronise anything.
#
# ⚠️ Multi-line handlers (prompts, conditionals) are emitted as one
#    line and MUST be read before this replaces the case block.

MENU=(
  "SECTION|ORCHESTRATION"
  "ITEM|Full spool-up (mock)|DTP_MOCK=1 $PY orchestrator.py --mock --no-gate"
  "ITEM|EOD aggregate (mock)|DTP_MOCK=1 $PY eod_report.py --mock"
  "ITEM|Reset mock state|reset_mock_state"
  "ITEM|Dry-run spool-up (real reads)|$PY orchestrator.py --dry-run --no-gate"
  "ITEM|Dry-run EOD aggregate (real reads)|$PY eod_report.py --dry-run"
  "SECTION|REGISTRY & MASTER SWITCH"
  "ITEM|Instance map|$PY instance_registry.py show"
  "ITEM|Reconcile map|$PY instance_registry.py reconcile"
  "ITEM|Swap / pin instance ID|$PY instance_registry.py swap"
  "ITEM|Control status|$PY control_state.py status"
  "ITEM|ENABLE control|$PY control_state.py enable"
  "ITEM|DISABLE control|$PY control_state.py disable"
  "SECTION|FLEET (inspect & fan-out)"
  "ITEM|Fleet list|$PY fleet.py list"
  "ITEM|Fleet ping|$PY fleet.py ping"
  "ITEM|Run command (all running)|read -rp \"Command to run on all running boxes: \" fc; $PY fleet.py run \"$fc\""
  "ITEM|status.py + query.py      (one/all/some)|SC=$(ask_scope); $PY fleet.py run \"cd $INSTALL_DIR; python status.py; echo; python query.py\" $SC"
  "ITEM|Pull trades.db            (one/all/some)|SC=$(ask_scope); $PY fleet.py pull db $SC"
  "ITEM|Pull OHLC for a day       (one/all/some)|SC=$(ask_scope); read -rp \"Day (YYYY-MM-DD, ENTER=today): \" D; D=\"${D:-$(date +%F)}\"; $PY fleet.py pull ohlc --day \"$D\" $SC"
  "SECTION|DEBUG / LOGS (remote; one/all/some)"
  "ITEM|Service status (bot + candle-feed)|SC=$(ask_scope); $PY fleet.py run 'echo \"optionsbot=$(systemctl is-active optionsbot) candle-feed=$(systemctl is-active candle-feed)\"' $SC"
  "ITEM|Journal tail (last N)|SC=$(ask_scope); read -rp \"How many journal lines [20]: \" N; N=\"${N:-20}\"; $PY fleet.py run \"journalctl -u optionsbot -n ${N} --no-pager\" $SC"
  "ITEM|Feed health (store freshness)|SC=$(ask_scope); $PY fleet.py run \"echo \"candle-feed= $(systemctl is-active candle-feed) store_write_age_s= $(( $(date +%s) - $(stat -c %Y ${FEED_DB}-wal 2>/dev/null || stat -c %Y ${FEED_DB} 2>/dev/null || echo 0) )) \"\" $SC"
  "ITEM|Bot log tail (last 20)|SC=$(ask_scope); $PY fleet.py run \"tail -20 ${INSTALL_DIR}/bot.log\" $SC"
  "SECTION|MAINTENANCE (wake_and_bake)"
  "ITEM|Dry-run|$PY wake_and_bake.py --dry-run"
  "ITEM|FULL (wake->bake->restart->STOP)|$PY wake_and_bake.py"
  "ITEM|Wake (one/all/some)|SC=$(ask_scope); $PY wake_and_bake.py --wake-only $SC"
  "ITEM|Bake only (sync, no restart - RTH-safe)|$PY wake_and_bake.py --bake-only"
  "ITEM|Leave on (skip shutdown)|$PY wake_and_bake.py --leave-running"
  "ITEM|EMERGENCY STOP (no EOD, no pycache, RTH-exempt, HALT-gated)|$PY wake_and_bake.py --shutdown-only"
  "SECTION|REPOINT (migrate fleet -> new repo)"
  "ITEM|Check only|U=$(ask_url); $PY fleet.py repoint \"$U\" --check-only"
  "ITEM|FULL|U=$(ask_url); $PY fleet.py repoint \"$U\""
  "ITEM|Full + wake|U=$(ask_url); $PY fleet.py repoint \"$U\" --wake"
  "ITEM|No restart|U=$(ask_url); $PY fleet.py repoint \"$U\" --no-restart"
  "ITEM|Scoped|U=$(ask_url); read -rp \"Symbols (comma-sep, e.g. SPX,QQQ): \" SY; $PY fleet.py repoint \"$U\" --only \"$SY\""
  "ITEM|Mock preview|U=$(ask_url); $PY fleet.py repoint \"$U\" --mock --yes"
  "SECTION|SNAPSHOT & TESTS"
  "ITEM|Snapshot dir -> repo-ready tarball|snapshot_dir"
  "ITEM|Test selection (mock)|$PY selector.py --test"
  "ITEM|Test Telegram (real)|$PY notify.py --test"
  "SECTION|CONTROL REPO (this checkout <-> GitHub, force sync)"
  "ITEM|PUSH -> GitHub  (FORCE; this server is source of truth)|repo_push_force"
  "ITEM|PULL <- GitHub  (FORCE; GitHub is source of truth)|repo_pull_force"
  "SECTION|TRADES DATA"
  "ITEM|Re-run consolidation -> fleet_trades_<date>.json (+ .csv)|read -rp \"Day to consolidate (YYYY-MM-DD, ENTER=today): \" D; D=\"${D:-$(date +%F)}\"; $PY consolidate_trades.py --date \"$D\""
  "ITEM|Excursion report (MFE/MAE) -> reports/excursions_<date>.txt|read -rp \"Day (YYYY-MM-DD, ENTER=today): \" D; D=\"${D:-$(date +%F)}\"; read -rp \"Cumulative since (YYYY-MM-DD, ENTER=that day only): \" S; read -rp \"Live rows? [y/N]: \" LV; ARGS=\"--date $D\"; [ -n \"$S\" ] && ARGS=\"$ARGS --since $S\"; [ \"$LV\" = \"y\" ] && ARGS=\"$ARGS --live\"; $PY excursion_report.py $ARGS"
  "ITEM|Trade breakdown (cross-day: regime/strategy/grade + regime x strategy)|read -rp \"Since date (YYYY-MM-DD, ENTER=all): \" SD; if [ -n \"$SD\" ]; then $PY trade_report.py --since \"$SD\"; else $PY trade_report.py; fi"
  "ITEM|FIT REPORT — everything for fitting in ONE text file (1 day or a range)|read -rp \"Day, or END of range (YYYY-MM-DD, ENTER=today): \" D; D=\"${D:-$(date +%F)}\"; read -rp \"Cumulative since (YYYY-MM-DD, ENTER=that day only): \" S; read -rp \"Skip the slow replay-corpus sections (ramps, A2 drift)? [y/N]: \" NS; ARGS=\"--date $D\"; [ -n \"$S\" ] && ARGS=\"$ARGS --since $S\"; [ \"$NS\" = \"y\" ] && ARGS=\"$ARGS --no-slow\"; echo \"Running — the replay-corpus sections take minutes; output is a FILE, not this screen.\"; $PY fit_report.py $ARGS"
  "SECTION|REGIME VALIDATION (Layer-1 confluence; manual, tape-only)"
  "ITEM|Run replay - today|if [ -x \"$VALIDATE_SH\" ]; then \"$VALIDATE_SH\"; else echo \"missing/non-exec $VALIDATE_SH (chmod +x $OTV3_DIR/validate_regime.sh?)\"; fi"
  "ITEM|Run replay - pick a date|read -rp \"Date (YYYY-MM-DD, ENTER=today): \" D; D=\"${D:-$(date +%F)}\"; if [ -x \"$VALIDATE_SH\" ]; then \"$VALIDATE_SH\" \"$D\"; else echo \"missing/non-exec $VALIDATE_SH\"; fi"
  "ITEM|View a day's report|D_DEF=\"$(date +%F)\"; read -rp \"Date to view (YYYY-MM-DD, ENTER=${D_DEF}): \" D; D=\"${D:-$D_DEF}\"; if [ -x \"$VALIDATE_SH\" ]; then \"$VALIDATE_SH\" --report \"$D\"; else echo \"missing/non-exec $VALIDATE_SH\"; fi"
  "ITEM|View the diary (all days)|if [ -x \"$VALIDATE_SH\" ]; then \"$VALIDATE_SH\" --diary; else echo \"missing/non-exec $VALIDATE_SH\"; fi"
  "ITEM|Backfill missing days      (fills diary gaps that have tape)|read -rp \"Rebuild ALL dated tapes (else only fill gaps)? [y/N]: \" RB; if [ -x \"$VALIDATE_SH\" ]; then if [ \"$RB\" = \"y\" ]; then \"$VALIDATE_SH\" --backfill --rebuild; else \"$VALIDATE_SH\" --backfill; fi; else echo \"missing/non-exec $VALIDATE_SH\"; fi"
  "ITEM|A2 co-occurrence + HTF drift  (read-only; auto-finds replay logs)|if [ -x \"$OTV3_PY\" ]; then (cd \"$OTV3_DIR\" && \"$OTV3_PY\" -m tests.a2_cooccurrence); else echo \"missing $OTV3_PY (is ~/options-trader-v3 checked out with its venv?)\"; fi"
  "SECTION|EOD CONDUCTOR, BACKFILL & LIVE P&L"
  "ITEM|Live P&L standings (read-only)|read -rp \"Push to Telegram too? [y/N]: \" S; if [ \"$S\" = \"y\" ]; then $PY standings.py --send; else $PY standings.py; fi"
  "ITEM|Backfill missing OHLC (auto-batched)|read -rp \"Backfill date (YYYY-MM-DD, ENTER=today): \" D; D=\"${D:-$(date +%F)}\"; read -rp \"Batch size (ENTER=5): \" B; B=\"${B:-5}\"; echo; $PY eod_backfill.py --date \"$D\" --batch \"$B\" --dry-run; echo; read -rp \"Proceed with LIVE backfill (wakes/stops boxes)? [y/N]: \" GO; [ \"$GO\" = \"y\" ] && $PY eod_backfill.py --date \"$D\" --batch \"$B\""
  "ITEM|EOD conductor - full gated EOD (dry-run preview -> confirm -> run)|read -rp \"Backfill batch size (ENTER=5): \" B; B=\"${B:-5}\"; echo; $PY eod_conductor.py --batch \"$B\" --dry-run; echo; read -rp \"Run the LIVE EOD conductor now (gate->harvest->P&L+stop->backfill->consolidate->diary)? [y/N]: \" GO; [ \"$GO\" = \"y\" ] && $PY eod_conductor.py --batch \"$B\""
  "SECTION|UTILITIES"
  "ITEM|OHLC 21-day fetch from yfinance (prompts symbol, default ^VIX)|read -rp \"Symbol [^VIX]: \" SY; SY=\"${SY:-^VIX}\"; $PY tests/ohlc_fetch.py --symbol \"$SY\""
  "ITEM|Rotate fleet tokens/secrets (pushes to running boxes)|read -rp \"Rotate against a SUBSET of symbols? (ENTER=all running): \" SUBSET; if [ -n \"$SUBSET\" ]; then $PY rotate_tokens.py --only $SUBSET; else $PY rotate_tokens.py; fi"
  "ITEM|Audit fleet credentials (read-only; shows which vars are set, no values)|read -rp \"Audit a SUBSET of symbols? (ENTER=all running): \" SUBSET; if [ -n \"$SUBSET\" ]; then $PY rotate_tokens.py --audit --only $SUBSET; else $PY rotate_tokens.py --audit; fi"
  "ITEM|Verify fleet credentials WORK (TT SDK, Telegram, GitHub)|read -rp \"Verify a SUBSET of symbols? (ENTER=all running): \" SUBSET; if [ -n \"$SUBSET\" ]; then $PY rotate_tokens.py --verify --only $SUBSET; else $PY rotate_tokens.py --verify; fi"
  "ITEM|Verify control IAM role sees the fleet (read-only; no start/stop)|$PY check_iam.py"
  "ITEM|Blind-alert DRILL on the fleet (sends REAL Telegram, marked DRILL)|echo \"Fires the REAL blind-alert path on every RUNNING box.\"; echo \"Each box sends TWO Telegram messages, both prefixed DRILL - NOT REAL.\"; echo \"READ THE PER-BOX 'DRILL PASSED/FAILED' LINE, NOT the 29/29 tally —\"; echo \"the tally cannot see the drill's exit code (v1.26).\"; read -rp \"Send for real? (n = dry-run, no Telegram) [y/N]: \" GO; if [ \"$GO\" = \"y\" ]; then $PY fleet.py run \"cd ~/options-trader && venv/bin/python tests/blind_alert_selftest.py 2>&1 | tail -4; true\"; else $PY fleet.py run \"cd ~/options-trader && venv/bin/python tests/blind_alert_selftest.py --no-send 2>&1 | tail -4; true\"; fi"
  "ITEM|Feed maintenance window (fleet up, nothing on the wire) - currently OFF|if _maint_on; then echo \"Feed maintenance is currently ACTIVE.\"; echo \"Turning it OFF lets every box feed again on its next gate check.\"; read -rp \"Turn maintenance OFF? [y/N]: \" GO; if [ \"$GO\" = \"y\" ]; then $PY fleet.py run \"rm -f ~/options-trader/data/FEED_MAINTENANCE; echo MAINT= $([ -f ~/options-trader/data/FEED_MAINTENANCE ] && echo ON || echo OFF)\" --all; rm -f \"$_MAINT_MARK\"; echo; echo \"Read the per-box MAINT= lines above - every one must say OFF.\"; echo \"A box still reading ON is still feed-silent and will trade blind.\"; fi; else echo \"Brings the fleet into a MAINTENANCE window: boxes can be up and\"; echo \"worked on (option 14, bakes, pushes) with NOTHING on the wire.\"; echo; echo \"The flag is checked live by candle_feed - no restart needed, and\"; echo \"it SURVIVES a bake. Nothing removes it but you.\"; echo \"!! A box left flagged at 09:15 trades blind. The menu line stays RED.\"; read -rp \"Turn maintenance ON? [y/N]: \" GO; if [ \"$GO\" = \"y\" ]; then $PY fleet.py run \"mkdir -p ~/options-trader/data && touch ~/options-trader/data/FEED_MAINTENANCE; echo MAINT= $([ -f ~/options-trader/data/FEED_MAINTENANCE ] && echo ON || echo OFF)\" --all; mkdir -p \"$SCRIPT_DIR/data\" && touch \"$_MAINT_MARK\"; echo; echo \"Read the per-box MAINT= lines above - every one must say ON.\"; echo \"A box that missed it is STILL FEEDING during your maintenance.\"; fi; fi; read -rp \"Enter to continue...\" _"
)

# ── render + dispatch, the whole of it ──────────────────────────────
# The number is a loop counter. It is never stored, never compared, and never
# written down anywhere — which is the entire point.
menu_render() {
  local i=0 kind rest
  for entry in "${MENU[@]}"; do
    IFS='|' read -r kind rest <<< "$entry"
    if [ "$kind" = "SECTION" ]; then
      printf '\n %s:\n' "$rest"
    else
      i=$((i+1)); printf '  %2d) %s\n' "$i" "${rest%%|*}"
    fi
  done
  printf '\n   0) Exit\n'
}

menu_dispatch() {
  local want="$1" i=0 kind rest
  [ "$want" = "0" ] && return 9
  for entry in "${MENU[@]}"; do
    IFS='|' read -r kind rest <<< "$entry"
    [ "$kind" = "SECTION" ] && continue
    i=$((i+1))
    if [ "$i" = "$want" ]; then eval "${rest#*|}"; return 0; fi
  done
  echo "no such option: $want"; return 1
}
