#!/usr/bin/env bash
# day_trader_pro/menu_registry.sh — GENERATED DRAFT, review before use
# Generated by tools/menu_extract.py from devtools.sh.
#
# THERE ARE NO NUMBERS IN THIS FILE. devtools.sh assigns them at
# render time from list position, so reordering this list, inserting
# a section, or deleting an item cannot desynchronise anything.
#
# Each ITEM names a function in menu_functions.sh — bodies are kept
# verbatim there, so multi-line handlers are not flattened.

MENU=(
  "SECTION|ORCHESTRATION"
  "ITEM|Full spool-up (mock)|mi_full_spool_up_mock"
  "ITEM|EOD aggregate (mock)|mi_eod_aggregate_mock"
  "ITEM|Reset mock state|mi_reset_mock_state"
  "ITEM|Dry-run spool-up (real reads)|mi_dry_run_spool_up_real_reads"
  "ITEM|Dry-run EOD aggregate (real reads)|mi_dry_run_eod_aggregate_real_reads"
  "SECTION|REGISTRY & MASTER SWITCH"
  "ITEM|Instance map|mi_instance_map"
  "ITEM|Reconcile map|mi_reconcile_map"
  "ITEM|Swap / pin instance ID|mi_swap_pin_instance_id"
  "ITEM|Control status|mi_control_status"
  "ITEM|ENABLE control|mi_enable_control"
  "ITEM|DISABLE control|mi_disable_control"
  "SECTION|FLEET (inspect & fan-out)"
  "ITEM|Fleet list|mi_fleet_list"
  "ITEM|Fleet ping|mi_fleet_ping"
  "ITEM|Run command (all running)|mi_run_command_all_running"
  "ITEM|status.py + query.py      (one/all/some)|mi_status_py_query_py_one_all_some"
  "ITEM|Pull trades.db            (one/all/some)|mi_pull_trades_db_one_all_some"
  "ITEM|Pull OHLC for a day       (one/all/some)|mi_pull_ohlc_for_a_day_one_all_some"
  "SECTION|DEBUG / LOGS (remote; one/all/some)"
  "ITEM|Service status (bot + candle-feed)|mi_service_status_bot_candle_feed"
  "ITEM|Journal tail (last N)|mi_journal_tail_last_n"
  "ITEM|Feed health (store freshness)|mi_feed_health_store_freshness"
  "ITEM|Bot log tail (last 20)|mi_bot_log_tail_last_20"
  "SECTION|MAINTENANCE (wake_and_bake)"
  "ITEM|Dry-run|mi_dry_run"
  "ITEM|FULL (wake->bake->restart->STOP)|mi_full_wake_bake_restart_stop"
  "ITEM|Wake (one/all/some)|mi_wake_one_all_some"
  "ITEM|Bake only (sync, no restart - RTH-safe)|mi_bake_only_sync_no_restart_rth_safe"
  "ITEM|Leave on (skip shutdown)|mi_leave_on_skip_shutdown"
  "ITEM|EMERGENCY STOP (no EOD, no pycache, RTH-exempt, HALT-gated)|mi_emergency_stop_no_eod_no_pycache_rth_exempt"
  "SECTION|REPOINT (migrate fleet -> new repo)"
  "ITEM|Check only|mi_check_only"
  "ITEM|FULL|mi_full"
  "ITEM|Full + wake|mi_full_wake"
  "ITEM|No restart|mi_no_restart"
  "ITEM|Scoped|mi_scoped"
  "ITEM|Mock preview|mi_mock_preview"
  "SECTION|SNAPSHOT & TESTS"
  "ITEM|Snapshot dir -> repo-ready tarball|mi_snapshot_dir_repo_ready_tarball"
  "ITEM|Test selection (mock)|mi_test_selection_mock"
  "ITEM|Test Telegram (real)|mi_test_telegram_real"
  "SECTION|CONTROL REPO (this checkout <-> GitHub, force sync)"
  "ITEM|PUSH -> GitHub  (FORCE; this server is source of truth)|mi_push_github_force_this_server_is_source_of_t"
  "ITEM|PULL <- GitHub  (FORCE; GitHub is source of truth)|mi_pull_github_force_github_is_source_of_truth"
  "SECTION|TRADES DATA"
  "ITEM|Re-run consolidation -> fleet_trades_<date>.json (+ .csv)|mi_re_run_consolidation_fleet_trades_date_json"
  "ITEM|Excursion report (MFE/MAE) -> reports/excursions_<date>.txt|mi_excursion_report_mfe_mae_reports_excursions"
  "ITEM|Trade breakdown (cross-day: regime/strategy/grade + regime x strategy)|mi_trade_breakdown_cross_day_regime_strategy_gr"
  "ITEM|FIT REPORT — everything for fitting in ONE text file (1 day or a range)|mi_fit_report_everything_for_fitting_in_one_tex"
  "SECTION|REGIME VALIDATION (Layer-1 confluence; manual, tape-only)"
  "ITEM|Run replay - today|mi_run_replay_today"
  "ITEM|Run replay - pick a date|mi_run_replay_pick_a_date"
  "ITEM|View a day's report|mi_view_a_day_s_report"
  "ITEM|View the diary (all days)|mi_view_the_diary_all_days"
  "ITEM|Backfill missing days      (fills diary gaps that have tape)|mi_backfill_missing_days_fills_diary_gaps_that"
  "ITEM|A2 co-occurrence + HTF drift  (read-only; auto-finds replay logs)|mi_a2_co_occurrence_htf_drift_read_only_auto_fi"
  "SECTION|EOD CONDUCTOR, BACKFILL & LIVE P&L"
  "ITEM|Live P&L standings (read-only)|mi_live_p_l_standings_read_only"
  "ITEM|Backfill missing OHLC (auto-batched)|mi_backfill_missing_ohlc_auto_batched"
  "ITEM|EOD conductor - full gated EOD (dry-run preview -> confirm -> run)|mi_eod_conductor_full_gated_eod_dry_run_preview"
  "SECTION|UTILITIES"
  "ITEM|OHLC 21-day fetch from yfinance (prompts symbol, default ^VIX)|mi_ohlc_21_day_fetch_from_yfinance_prompts_symb"
  "ITEM|Rotate fleet tokens/secrets (pushes to running boxes)|mi_rotate_fleet_tokens_secrets_pushes_to_runnin"
  "ITEM|Audit fleet credentials (read-only; shows which vars are set, no values)|mi_audit_fleet_credentials_read_only_shows_whic"
  "ITEM|Verify fleet credentials WORK (TT SDK, Telegram, GitHub)|mi_verify_fleet_credentials_work_tt_sdk_telegra"
  "ITEM|Verify control IAM role sees the fleet (read-only; no start/stop)|mi_verify_control_iam_role_sees_the_fleet_read"
  "ITEM|Blind-alert DRILL on the fleet (sends REAL Telegram, marked DRILL)|mi_blind_alert_drill_on_the_fleet_sends_real_te"
  "ITEM|Feed maintenance window (fleet up, nothing on the wire) - currently OFF|mi_feed_maintenance_window_fleet_up_nothing_on"
)

# ── render + dispatch, the whole of it ──────────────────────────────
# The number is a loop counter. It is never stored, never compared, and never
# written down anywhere — which is the entire point.
# One item's label is LIVE, not static: the feed-maintenance row turns red when
# the flag is on. It used to be printed between two heredocs for exactly this
# reason. Here it is a label override, so the item stays in the list like any
# other and nothing special-cases its position.
_menu_label() {
  case "$1" in
    "Feed maintenance window"*)
      if _maint_on; then
        printf '%s' "${_RED}*** FEED MAINTENANCE IS ACTIVE - no tape is being collected ***${_RST}"
      else
        printf '%s' "Feed maintenance window (fleet up, nothing on the wire) - currently OFF"
      fi ;;
    *) printf '%s' "$1" ;;
  esac
}

menu_render() {
  printf '======================================================\n'
  printf '  Day Trader Pro — devtools  v1.32 Service Menu\n'
  printf '======================================================\n'
  local i=0 kind rest label
  for entry in "${MENU[@]}"; do
    IFS='|' read -r kind rest <<< "$entry"
    if [ "$kind" = "SECTION" ]; then
      printf '\n %s:\n' "$rest"
    else
      i=$((i+1)); label="$(_menu_label "${rest%%|*}")"
      printf '  %2d) %s\n' "$i" "$label"
    fi
  done
  printf '\n   0) Exit\n'
  printf '======================================================\n'
}

menu_dispatch() {
  local want="$1" i=0 kind rest
  [ "$want" = "0" ] && return 9
  for entry in "${MENU[@]}"; do
    IFS='|' read -r kind rest <<< "$entry"
    [ "$kind" = "SECTION" ] && continue
    i=$((i+1))
    if [ "$i" = "$want" ]; then eval "${rest#*|}"; return 0; fi
  done
  echo "no such option: $want"; return 1
}
