#!/usr/bin/env bash
# day_trader_pro/menu_registry.sh — GENERATED DRAFT, review before use
# Generated by tools/menu_extract.py from devtools.sh.
#
# THERE ARE NO NUMBERS IN THIS FILE. devtools.sh assigns them at
# render time from list position, so reordering this list, inserting
# a section, or deleting an item cannot desynchronise anything.
#
# Each ITEM names a function in menu_functions.sh — bodies are kept
# verbatim there, so multi-line handlers are not flattened.

MENU=(
  "SECTION|ORCHESTRATION"
  "ITEM|Full spool-up (mock)|mi_full_spool_up_mock"
  "ITEM|EOD aggregate (mock)|mi_eod_aggregate_mock"
  "ITEM|Reset mock state|mi_reset_mock_state"
  "ITEM|Dry-run spool-up (real reads)|mi_dry_run_spool_up_real_reads"
  "ITEM|Dry-run EOD aggregate (real reads)|mi_dry_run_eod_aggregate_real_reads"
  "SECTION|REGISTRY & MASTER SWITCH"
  "ITEM|Instance map|mi_instance_map"
  "ITEM|Reconcile map|mi_reconcile_map"
  "ITEM|Swap / pin instance ID|mi_swap_pin_instance_id"
  "ITEM|Control status|mi_control_status"
  "ITEM|ENABLE control|mi_enable_control"
  "ITEM|DISABLE control|mi_disable_control"
  "SECTION|FLEET (inspect & fan-out)"
  "ITEM|Fleet list|mi_fleet_list"
  "ITEM|Fleet ping|mi_fleet_ping"
  "ITEM|Run command (all running)|mi_run_command_all_running"
  "ITEM|status.py + query.py      (one/all/some)|mi_status_py_query_py_one_all_some"
  "ITEM|Pull trades.db            (one/all/some)|mi_pull_trades_db_one_all_some"
  "ITEM|Pull OHLC for a day       (one/all/some)|mi_pull_ohlc_for_a_day_one_all_some"
  "ITEM|Hotfix launcher (repo synch & flush)|mi_hotfix_launcher_repo_synch_flush"
  "SECTION|SENSORS (derived stores; read-only, one/all/some)"
  "ITEM|Manifold health board|mi_manifold_health_board"
  "ITEM|Strategy notes        (what each engine SAW)|mi_sensor_strategy_notes"
  "ITEM|Plan ledger           (intent + terminal reason)|mi_sensor_plan_ledger"
  "ITEM|Exit counterfactual   (flow vs the stop)|mi_sensor_exit_counterfactual"
  "ITEM|Fire snapshot         (derived vector at entry)|mi_sensor_fire_snapshot"
  "ITEM|Surface               (charm / vanna / GEX)|mi_sensor_surface"
  "ITEM|Indicators            (ADX / ATR / VWAP series)|mi_sensor_indicators"
  "ITEM|Forks                 (built vs reject reason)|mi_sensor_forks"
  "ITEM|Levels                (touches + retirements)|mi_sensor_levels"
  "ITEM|Order flow            (aggression + depth)|mi_sensor_order_flow"
  "SECTION|DEBUG / LOGS (remote; one/all/some)"
  "ITEM|Service status (bot + candle-feed)|mi_service_status_bot_candle_feed"
  "ITEM|Journal tail (last N)|mi_journal_tail_last_n"
  "ITEM|Feed health (store freshness)|mi_feed_health_store_freshness"
  "ITEM|Bot log tail (last 20)|mi_bot_log_tail_last_20"
  "SECTION|MAINTENANCE (wake_and_bake)"
  "ITEM|Retire — off-hours stop (one/all/some)|mi_retire_one_all_some"
  "ITEM|FULL (wake->bake->restart->STOP)|mi_full_wake_bake_restart_stop"
  "ITEM|Wake|mi_wake_one_all_some"
  "ITEM|Bake only (sync, no restart - RTH-safe)|mi_bake_only_sync_no_restart_rth_safe"
  "ITEM|Leave on (skip shutdown)|mi_leave_on_skip_shutdown"
  "ITEM|EMERGENCY STOP — mid-session, abandons positions (one/all/some)|mi_emergency_stop_no_eod_no_pycache_rth_exempt"
  "SECTION|REPOINT (migrate fleet -> new repo)"
  "ITEM|Check only|mi_check_only"
  "ITEM|FULL|mi_full"
  "ITEM|Full + wake|mi_full_wake"
  "ITEM|No restart|mi_no_restart"
  "ITEM|Scoped|mi_scoped"
  "ITEM|Mock preview|mi_mock_preview"
  "SECTION|SNAPSHOT & TESTS"
  "ITEM|Snapshot dir -> repo-ready tarball|mi_snapshot_dir_repo_ready_tarball"
  "ITEM|Test selection (mock)|mi_test_selection_mock"
  "ITEM|Test Telegram (real)|mi_test_telegram_real"
  "SECTION|CONTROL REPO (this checkout <-> GitHub, force sync)"
  "ITEM|PUSH -> GitHub  (FORCE; this server is source of truth)|mi_push_github_force_this_server_is_source_of_t"
  "ITEM|PULL <- GitHub  (FORCE; GitHub is source of truth)|mi_pull_github_force_github_is_source_of_truth"
  "SECTION|TRADES DATA"
  "ITEM|Re-run consolidation -> fleet_trades_<date>.json (+ .csv)|mi_re_run_consolidation_fleet_trades_date_json"
  "ITEM|Excursion report (MFE/MAE) -> reports/excursions_<date>.txt|mi_excursion_report_mfe_mae_reports_excursions"
  "ITEM|Trade breakdown (cross-day: strategy/grade/setup)|mi_trade_breakdown_cross_day"
  "ITEM|FIT REPORT — everything for fitting in ONE text file (1 day or a range)|mi_fit_report_everything_for_fitting_in_one_tex"
  "SECTION|EOD CONDUCTOR, BACKFILL & LIVE P&L"
  "ITEM|Live P&L standings (reads the BOXES; must be up)|mi_live_p_l_standings_read_only"
  "ITEM|P&L from WAREHOUSE (day or range; boxes off)|mi_pnl_from_warehouse"
  "ITEM|EOD analysis — all reports from S3 (boxes off)|mi_eod_analysis"
  "ITEM|Backfill missing OHLC (auto-batched)|mi_backfill_missing_ohlc_auto_batched"
  "ITEM|EOD conductor - full gated EOD (dry-run preview -> confirm -> run)|mi_eod_conductor_full_gated_eod_dry_run_preview"
  "SECTION|UTILITIES"
  "ITEM|OHLC 21-day fetch from yfinance (prompts symbol, default ^VIX)|mi_ohlc_21_day_fetch_from_yfinance_prompts_symb"
  "ITEM|Rotate fleet tokens/secrets (pushes to running boxes)|mi_rotate_fleet_tokens_secrets_pushes_to_runnin"
  "ITEM|Audit fleet credentials (read-only; shows which vars are set, no values)|mi_audit_fleet_credentials_read_only_shows_whic"
  "ITEM|Verify fleet credentials WORK (TT SDK, Telegram, GitHub)|mi_verify_fleet_credentials_work_tt_sdk_telegra"
  "ITEM|Verify control IAM role sees the fleet (read-only; no start/stop)|mi_verify_control_iam_role_sees_the_fleet_read"
  "ITEM|Blind-alert DRILL on the fleet (sends REAL Telegram, marked DRILL)|mi_blind_alert_drill_on_the_fleet_sends_real_te"
  "ITEM|Feed maintenance window (fleet up, nothing on the wire) - currently OFF|mi_feed_maintenance_window_fleet_up_nothing_on"
  "SECTION|S3 WAREHOUSE (read-only; runs ALONGSIDE the local reports)"
  "ITEM|Warehouse inventory & cost|mi_warehouse_inventory_cost"
  "ITEM|Warehouse inventory & cost (+ noncurrent versions)|mi_warehouse_inventory_versions"
  "ITEM|Rebuild a day's bundle FROM S3 -> reports/warehouse/|mi_warehouse_rebuild_bundle"
  "ITEM|Compare S3 vs local - one date|mi_warehouse_compare_date"
  "ITEM|Compare S3 vs local - EVERY in-coverage date|mi_warehouse_compare_all"
  "ITEM|Explain a date's divergence (lists trade_ids)|mi_warehouse_explain_date"
  "ITEM|Excursion report FROM THE WAREHOUSE|mi_warehouse_excursion_report"
  "ITEM|Trade breakdown FROM THE WAREHOUSE (cross-day)|mi_warehouse_trade_report"
  "ITEM|REPORT PARITY - run 40 & 41 both sources, diff OUTPUTS|mi_warehouse_report_parity"
)

# ── render + dispatch, the whole of it ──────────────────────────────
# The number is a loop counter. It is never stored, never compared, and never
# written down anywhere — which is the entire point.
# One item's label is LIVE, not static: the feed-maintenance row turns red when
# the flag is on. It used to be printed between two heredocs for exactly this
# reason. Here it is a label override, so the item stays in the list like any
# other and nothing special-cases its position.
_menu_label() {
  case "$1" in
    "Feed maintenance window"*)
      if _maint_on; then
        printf '%s' "${_RED}*** FEED MAINTENANCE IS ACTIVE - no tape is being collected ***${_RST}"
      else
        printf '%s' "Feed maintenance window (fleet up, nothing on the wire) - currently OFF"
      fi ;;
    *) printf '%s' "$1" ;;
  esac
}

# ── 🔴 THE BANNER READS ITS VERSION FROM devtools.sh, IT IS NOT TYPED HERE ──
# It said "v1.35" against a v1.39 header on 2026-08-25 — FOUR revisions stale,
# and it had drifted before: the file's own v1.28 note records the banner
# reading v1.26 while the header had moved on.
#
# ⚠️ THE CAUSE IS THAT THE BANNER LIVES IN A DIFFERENT FILE FROM THE HEADER IT
# QUOTES. Bumping devtools.sh cannot move a literal in menu_registry.sh, so the
# standing "title == newest changelog entry" rule was being followed and the
# banner still lied. A rule that a careful person can obey while the output
# stays wrong is not a rule, it is a trap.
#
# ⚠️ DERIVED, NOT DUPLICATED. There is now ONE place the version is written.
_devtools_version() {
  local d="${BASH_SOURCE%/*}/devtools.sh"
  sed -n 's/^# day_trader_pro\/devtools\.sh — \(v[0-9.]*\).*/\1/p' "$d" \
    2>/dev/null | head -1
}

menu_render() {
  local _ver
  _ver="$(_devtools_version)"
  [ -z "$_ver" ] && _ver="(version unreadable)"
  printf '======================================================\n'
  printf '  Day Trader Pro — devtools  %s Service Menu\n' "$_ver"
  printf '======================================================\n'
  local i=0 kind rest label
  for entry in "${MENU[@]}"; do
    IFS='|' read -r kind rest <<< "$entry"
    if [ "$kind" = "SECTION" ]; then
      printf '\n %s:\n' "$rest"
    else
      i=$((i+1)); label="$(_menu_label "${rest%%|*}")"
      printf '  %2d) %s\n' "$i" "$label"
    fi
  done
  printf '\n   0) Exit\n'
  printf '======================================================\n'
}

menu_dispatch() {
  local want="$1" i=0 kind rest
  [ "$want" = "0" ] && return 9
  for entry in "${MENU[@]}"; do
    IFS='|' read -r kind rest <<< "$entry"
    [ "$kind" = "SECTION" ] && continue
    i=$((i+1))
    if [ "$i" = "$want" ]; then eval "${rest#*|}"; return 0; fi
  done
  echo "no such option: $want"; return 1
}
