#!/usr/bin/env python3
"""
day_trader_pro/tools/trades_epoch_strip_check.py  v1.0
v1.0  2026-09-07  dtp r314 / S3.22 — THE LAND GATE FOR THE EPOCH STRIP.

WHY A WRAPPER AND NOT THE TOOL'S OWN FLAG. `land.sh` runs each declared check
as `python3 "$chk"` with `$chk` as ONE QUOTED ARGUMENT, so a `CHECK` directive
is a SCRIPT PATH — no interpreter prefix, no arguments. `CHECK
tools/trades_epoch_strip.py --selftest` would be run as a filename containing
spaces, which is how dtp r311 failed. And a bare `CHECK tools/trades_epoch_strip.py`
would run the REAL SCAN against the live bucket during a land, which is worse
than a broken gate: a land command must not touch the warehouse.

⚠️ THIS FILE EXISTS BECAUSE I TOOK A SHORTCUT AND THE GATE CAUGHT IT. The
first version was generated by a `printf` inside a shell pipeline — it carried
a version string and no dated changelog entry, and `check_land_discipline`
refused the delivery on exactly that (§5: the version lives in TWO places and
both must move). WORKING_AGREEMENT §0.3 records the pattern: the shortcut
correlates with how small the task is judged to be, and eight lines read as
too small to write properly.

It runs the tool's selftest in-process via `runpy` so the guards are EXECUTED,
not imported and inspected — the whole value of that selftest is that E7
attempts a forbidden delete and proves it is refused.

Run:  python3 tools/trades_epoch_strip_check.py
"""
from __future__ import annotations

import os
import runpy
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_TOOL = os.path.join(_HERE, "trades_epoch_strip.py")


def main() -> int:
    if not os.path.exists(_TOOL):
        # ⚠️ A missing tool is a PATH FAULT, not a passing gate. Saying so
        # beats exiting 0 on a file that is not there.
        print(f"  🔴 {_TOOL} missing — this gate has nothing to run.")
        return 1
    sys.argv = ["trades_epoch_strip.py", "--selftest"]
    try:
        runpy.run_path(_TOOL, run_name="__main__")
    except SystemExit as exc:
        return int(exc.code or 0)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
